# Generated by Django 3.2.7 on 2022-06-05 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id_Citizen', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.SmallIntegerField()),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id_Community', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id_Gym', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('element_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('element_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.element')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_Region', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('legendary', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pokemonApp.community')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id_village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pokemonApp.community')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.gym')),
                ('id_Trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.citizen')),
            ],
            options={
                'unique_together': {('id_Trainer', 'id_Gym')},
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id_Pokemon', models.IntegerField(primary_key=True, serialize=False)),
                ('height', models.DecimalField(decimal_places=2, max_digits=7)),
                ('shine', models.BooleanField()),
                ('sex', models.CharField(max_length=1)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('nature', models.CharField(max_length=15)),
                ('id_Trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.trainer')),
                ('species_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.species')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='id_Region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pokemonApp.region'),
        ),
        migrations.CreateModel(
            name='Species_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.region')),
                ('name_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.species')),
            ],
            options={
                'unique_together': {('name_species', 'id_Region')},
            },
        ),
        migrations.CreateModel(
            name='Species_Motion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.motion')),
                ('name_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.species')),
            ],
            options={
                'unique_together': {('name_species', 'name_motion')},
            },
        ),
        migrations.CreateModel(
            name='Species_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.element')),
                ('name_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.species')),
            ],
            options={
                'unique_together': {('name_species', 'name_element')},
            },
        ),
        migrations.CreateModel(
            name='Gym_Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.gym')),
                ('id_Trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.trainer')),
            ],
            options={
                'unique_together': {('id_Trainer', 'id_Gym')},
            },
        ),
        migrations.AddField(
            model_name='gym',
            name='id_City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.city'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='id_City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.city'),
        ),
        migrations.CreateModel(
            name='CaughtPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=15)),
                ('pokeball', models.CharField(max_length=15)),
                ('caught_level', models.IntegerField()),
                ('actual_level', models.IntegerField()),
                ('id_Pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.pokemon')),
                ('id_Trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.trainer')),
            ],
            options={
                'unique_together': {('id_Trainer', 'id_Pokemon')},
            },
        ),
        migrations.CreateModel(
            name='Caught_Pokemon_Motion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.pokemon')),
                ('id_Trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.trainer')),
                ('name_motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonApp.motion')),
            ],
            options={
                'unique_together': {('name_motion', 'id_Pokemon', 'id_Trainer')},
            },
        ),
    ]
