# Generated by Django 3.2.7 on 2022-06-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='strong_vs',
            field=models.ManyToManyField(blank=True, related_name='_pokemonApp_element_strong_vs_+', to='pokemonApp.Element'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='oponent',
            field=models.ManyToManyField(related_name='_pokemonApp_trainer_oponent_+', through='pokemonApp.Duel', to='pokemonApp.Trainer'),
        ),
    ]
