# Generated by Django 3.2.7 on 2022-06-05 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id_City',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pokemonApp.community'),
        ),
    ]
