# Generated by Django 4.0.5 on 2022-06-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonApp', '0002_auto_20220619_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caughtpokemon',
            name='actual_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='caughtpokemon',
            name='caught_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='caughtpokemon',
            name='motion',
            field=models.ManyToManyField(max_length=4, to='pokemonApp.motion'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='element',
            name='strong_vs',
            field=models.ManyToManyField(blank=True, to='pokemonApp.element'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='oponent',
            field=models.ManyToManyField(through='pokemonApp.Duel', to='pokemonApp.trainer'),
        ),
    ]
