# Generated by Django 3.2.7 on 2022-06-05 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonApp', '0002_alter_city_id_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='id_village',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pokemonApp.community'),
        ),
    ]
