# Generated by Django 4.0.5 on 2022-06-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonApp', '0003_alter_caughtpokemon_actual_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caughtpokemon',
            name='motion',
            field=models.ManyToManyField(limit_choices_to=4, to='pokemonApp.motion'),
        ),
    ]
