# Generated by Django 4.0.5 on 2022-06-20 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonApp', '0004_alter_caughtpokemon_motion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalMotion',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pokemonApp.motion')),
            ],
        ),
        migrations.CreateModel(
            name='TaughtMotion',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pokemonApp.motion')),
            ],
        ),
        migrations.AlterField(
            model_name='caughtpokemon',
            name='motion',
            field=models.ManyToManyField(to='pokemonApp.motion'),
        ),
    ]
